     name: CI/CD

     on:
       push:
         branches: [ main ]

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'

         - name: Install Angular dependencies
           run: npm install
           working-directory: free-collab-frontend

         - name: Build Angular app
           run: ng build --prod
           working-directory: free-collab-frontend

         - name: Set up .NET
           uses: actions/setup-dotnet@v2
           with:
             dotnet-version: '6.0.x'

         - name: Build .NET app
           run: dotnet build
           working-directory: FreeCollabBackend

         - name: Test .NET app
           run: dotnet test
           working-directory: FreeCollabBackend